image: nimlang/nim

variables:
  XDG_CACHE_HOME: ${CI_PROJECT_DIR}/.cache
  NIMBLE_DIR: ${CI_PROJECT_DIR}/.nimble
  PROJECT: nimflux
  DOCKER_INFLUXDB_INIT_USERNAME: nimflux
  DOCKER_INFLUXDB_INIT_PASSWORD: nimflux
  DOCKER_INFLUXDB_INIT_ORG: nimflux
  DOCKER_INFLUXDB_INIT_BUCKET: nimtest


cache:
  paths:
    - /apt-cache
    - ${XDG_CACHE_HOME}
    - ${NIMBLE_DIR}


stages:
  - test
  - docs

before_script:
  - export PATH="${PATH}:${NIMBLE_DIR}/bin"
  - mkdir -p ${NIMBLE_DIR} ${XDG_CACHE_HOME}

tests:
  services:
    - influxdb:1.8
  script:
    - nimble test -y > tests.log
  artifacts:
    paths:
      - tests.log

documentation:
  stage: docs
  script:
    - mkdir -p docs
    - nimble doc --project --index:on --outdir:public src/${PROJECT}.nim
  artifacts:
    paths:
      - docs
